### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by webwurst** [giantswarm/kube-app-testing#23]
Most components have updates, some of them with major changes like switching to helm3.

**Comment by cokiengchiara** [comment]
Please remember to share w @sslavic if will help.

**Comment by cokiengchiara** [comment]
@webwurst what's the status of this issue? IIUC, we shouldn't do this until Helm 3 is released in TCs? cc @sslavic and @piontec

**Comment by cokiengchiara** [comment]
Moving this to blocked. Not sure what to do about this. @webwurst pls update when you're back :)

**Comment by cokiengchiara** [comment]
Closing as I don't know what it is and @webwurst has not answered.
